# Generated by Django 6.0 on 2026-01-18 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicine_billing_doctor_fee_billing_medicine_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='billing',
            name='bill_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('treatment', 'Treatment'), ('medicine', 'Medicine'), ('room', 'Room Charges'), ('surgery', 'Surgery'), ('emergency', 'Emergency'), ('other', 'Other')], default='consultation', max_length=20),
        ),
        migrations.AddField(
            model_name='billing',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='insurance_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('insurance', 'Insurance')], default='cash', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.billing')),
            ],
        ),
    ]
