# Generated by Django 6.0 on 2026-01-19 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_amount_billing_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='core.appointment'),
        ),
    ]
